# Generated by Django 5.0.6 on 2024-06-19 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0010_alter_subcategory_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_super_admin',
        ),
    ]
